// this file is auto-generated by the command: php artisan typescript:transform
// do not edit this file manually
declare namespace App {
namespace Data {
export type AdviceData = {
first_name: string,
last_name: string,
street: string,
street_number: string,
zip: string,
city: string,
email: string,
phone: string,
commentary: string | null,
advisor_id: string | null,
advice_status_id: string | null,
lng: number | null,
lat: number | null,
type: App.Enums.AdviceType,
help_type_place: boolean,
help_type_technical: boolean,
help_type_bureaucracy: boolean,
help_type_other: boolean,
house_type: App.Enums.HouseType | null,
landlord_exists: boolean | null,
place_notes: string | null,
shares_ids: string[],
distance: number | null,
can_edit: boolean,
};
export type AdviceEventData = {
id: string,
description: string,
created_at: string,
user_name: string | null,
initials: string | null,
type: string,
subject: string | null,
content: string | null,
to: string | null,
};
export type AdviceStatusData = {
id: string,
name: string,
result: App.Enums.AdviceStatusResult,
group_id: string | null,
visible_in_group: boolean,
};
export type AdviceStatusNamesData = {
id: string,
name: string,
result: App.Enums.AdviceStatusResult,
};
export type ChecklistEntryData = {
id: string,
form_definition: App.Data.FormDefinitionData,
fields: App.Data.ChecklistEntryFieldData[],
updated_at: string,
};
export type ChecklistEntryFieldData = {
field: App.Data.FormFieldData,
value: number | string | string[] | null,
};
export type CrmUserData = {
id: string,
name: string,
email: string,
};
export type DataProtectedAdviceData = {
id: string,
first_name: string,
last_name: string,
street: string,
street_number: string,
zip: string,
city: string,
email: string | null,
phone: string | null,
commentary: string | null,
advisor_id: string | null,
advice_status_id: string | null,
lng: number | null,
lat: number | null,
type: App.Enums.AdviceType | null,
created_at: string,
updated_at: string,
distance: number | null,
shares_ids: string[],
place_notes: string | null,
house_type: App.Enums.HouseType | null,
landlord_exists: boolean | null,
help_type_place: boolean | null,
help_type_technical: boolean | null,
help_type_bureaucracy: boolean | null,
help_type_other: boolean | null,
result: App.Enums.AdviceStatusResult,
can_edit: boolean | null,
group_id: string | null,
nextcloud_folder_id: string | null,
nextcloud_folder_path: string | null,
};
export type FormDefinitionData = {
id: string,
name: string,
description: string | null,
is_active: boolean,
fields: App.Data.FormFieldData[],
group_id: string,
advice_mapping: App.Data.FormToAdviceMappingData | null,
map_point_mapping: App.Data.FormToMapPointMappingData | null,
success_message: string | null,
show_next_form_button: boolean,
next_form_button_text: string | null,
type: App.Enums.FormType,
allowed_embed_domains: string[] | null,
};
export type FormFieldData = {
id: string,
type: App.Enums.FieldType,
label: string,
options: App.Data.FormFieldOptionData[],
placeholder: string | null,
help_text: string | null,
required: boolean,
default_value: string | null,
sort_order: number,
min_length: number | null,
max_length: number | null,
min_value: number | null,
max_value: number | null,
accepted_file_types: string[] | null,
max_images: number,
};
export type FormFieldOptionData = {
id: string,
label: string,
value: string,
sort_order: number,
is_default: boolean,
is_required: boolean,
};
export type FormSubmissionData = {
id: string,
form_name: string,
fields: App.Data.SubmissionFieldData[],
submitted_at: string,
seen: boolean,
};
export type FormToAdviceMappingData = {
enabled: boolean,
first_name_field_id: string | null,
last_name_field_id: string | null,
address_field_id: string | null,
email_field_id: string | null,
phone_field_id: string | null,
advice_type_field_id: string | null,
advice_type_direct: string | null,
advice_type_home_option_value: string | null,
advice_type_virtual_option_value: string | null,
default_group_id: string | null,
};
export type FormToMapPointMappingData = {
enabled: boolean,
title_field_id: string | null,
description_field_id: string | null,
coordinate_field_id: string | null,
};
export type GroupBaseData = {
id: string,
name: string,
description: string | null,
logo_path: string | null,
};
export type GroupData = {
users_count: number,
advices_count: number,
id: string,
name: string,
description: string | null,
url: string | null,
logo_path: string | null,
marker_path: string | null,
parent_id: string | null,
accepts_transfers: boolean,
userCanActAsAdmin: boolean,
new_advice_mail: string | null,
nextcloud_group_name: string | null,
primary_hue: number | null,
primary_lightness: number | null,
primary_chroma: number | null,
};
export type GroupMapData = {
polygon: App.ValueObjects.Polygon,
center: App.ValueObjects.Coordinate,
name: string,
logo_path: string | null,
};
export type GroupTreeItem = {
id: string,
name: string,
selected: boolean,
expanded: boolean,
parent_id: string | null,
logo_path: string | null,
};
export type GroupUserData = {
id: string,
name: string,
email: string,
is_admin: boolean,
is_active: boolean,
};
export type MailBodyData = {
readonly uid: string,
readonly folder: string,
readonly subject: string,
readonly from: string,
readonly to: string,
readonly date: string,
readonly body: string,
};
export type MailConfigData = {
readonly imapHost: string,
readonly imapPort: number,
readonly smtpHost: string,
readonly smtpPort: number,
readonly username: string,
};
export type MailHeaderData = {
readonly uid: string,
readonly folder: string,
readonly subject: string,
readonly from: string,
readonly date: string,
readonly hasBeenRead: boolean,
readonly dateTimestamp: number,
};
export type MapEmbedData = {
id: string,
name: string | null,
categories: App.Data.MapPointCategoryData[],
coordinate: App.ValueObjects.Coordinate,
zoom: number,
show_table: boolean,
group_id: string | null,
group_name: string | null,
aspect_ratio_width: number,
aspect_ratio_height: number,
created_at: string | null,
};
export type MapPointCategoryData = {
id: string,
name: string,
image_path: string | null,
map_points_count: number,
created_at: string | null,
};
export type MapPointData = {
id: string,
coordinate: App.ValueObjects.Coordinate,
title: string,
description: string,
published: boolean,
userReadablePointableType: string,
created_at: string,
category_id: string | null,
location: string | null,
};
export type NextcloudGroupUserData = {
nc_id: string | null,
nc_email: string | null,
nc_displayname: string | null,
nc_enabled: boolean | null,
crm_user: App.Data.CrmUserData | null,
crm_is_group_member: boolean | null,
};
export type PaginationData<TValue> = {
total: number,
perPage: number,
currentPage: number,
lastPage: number,
};
export type StatusDistributionPointData = {
date: string,
statusCounts: Record<string, number>,
};
export type StatusNameCountData = {
name: string,
result: App.Enums.AdviceStatusResult,
count: number,
};
export type SubmissionFieldData = {
value: number | string | string[] | null,
field: App.Data.FormFieldData,
};
export type UserData = {
id: string,
first_name: string,
last_name: string,
name: string,
email: string,
is_acting_as_admin: boolean,
lat: number | null,
long: number | null,
profile_picture: string | null,
advice_radius: number | null,
street: string | null,
street_number: string | null,
city: string | null,
zip: string | null,
is_admin: boolean,
is_active: boolean,
groups: App.Data.GroupBaseData[],
};
export type YearlyAdviceCountData = {
label: string,
counts: number[],
};
namespace Pages {
export type GroupsIndexData = {
groupTreeItems: App.Data.GroupTreeItem[],
groups: App.Data.GroupData[],
canCreateRootGroup: boolean,
selectedGroup: App.Data.GroupData | null,
polygon: App.ValueObjects.Polygon | null,
canEditGroup: boolean,
canCreateGroups: boolean,
groupUsers: App.Data.GroupUserData[] | null,
};
}
}
namespace Enums {
export type AdviceStatusResult = 0 | 1 | 2 | 3;
export type AdviceType = 0 | 1 | 2;
export type Aggregation = 'day' | 'week' | 'month' | 'quarter';
export type FieldType = 'text' | 'textarea' | 'number' | 'email' | 'phone' | 'select' | 'radio' | 'checkbox' | 'file' | 'image' | 'date' | 'geo_coordinate' | 'address';
export type FormType = 0 | 1;
export type HouseType = 0 | 1 | 2;
}
namespace Nextcloud {
namespace Data {
export type NextcloudDir = {
readonly fileId: string,
readonly path: string,
readonly name: string,
};
export type NextcloudFile = {
readonly fileId: string,
readonly path: string,
readonly name: string,
readonly size: number,
readonly mimeType: string,
readonly lastModified: string,
};
export type NextcloudUser = {
readonly id: string,
readonly email: string,
readonly displayname: string,
readonly enabled: boolean,
readonly groups: string[],
};
}
}
namespace ValueObjects {
export type Address = {
street: string,
street_number: string,
zip: string,
city: string,
};
export type Coordinate = {
readonly lat: number,
readonly lng: number,
};
export type Polygon = {
readonly coordinates: (App.ValueObjects.Coordinate | {
lat: number,
lng: number,
})[],
};
}
}
declare namespace Illuminate {
export type CursorPaginator<TKey, TValue> = {
data: TKey extends string ? Record<TKey, TValue> : TValue[],
links: {
url: string | null,
label: string,
active: boolean,
}[],
meta: {
path: string,
per_page: number,
next_cursor: string | null,
next_page_url: string | null,
prev_cursor: string | null,
prev_page_url: string | null,
},
};
export type CursorPaginatorInterface<TKey, TValue> = Illuminate.CursorPaginator<TKey, TValue>;
export type LengthAwarePaginator<TKey, TValue> = {
data: TKey extends string ? Record<TKey, TValue> : TValue[],
links: {
url: string | null,
label: string,
active: boolean,
}[],
meta: {
total: number,
current_page: number,
first_page_url: string,
from: number | null,
last_page: number,
last_page_url: string,
next_page_url: string | null,
path: string,
per_page: number,
prev_page_url: string | null,
to: number | null,
},
};
export type LengthAwarePaginatorInterface<TKey, TValue> = Illuminate.LengthAwarePaginator<TKey, TValue>;
}
declare namespace Spatie {
namespace LaravelData {
export type CursorPaginatedDataCollection<TKey, TValue> = Illuminate.CursorPaginator<TKey, TValue>;
export type PaginatedDataCollection<TKey, TValue> = Illuminate.LengthAwarePaginator<TKey, TValue>;
}
}
