// this file is auto-generated by the command: php artisan typescript:transform
// do not edit this file manually
declare namespace App.Data {
export type AdviceEventData = {
id: string;
description: string;
created_at: string;
user_name: string | null;
initials: string | null;
type: string;
subject: string | null;
content: string | null;
to: string | null;
};
export type AdviceStatusData = {
id: string;
name: string;
result: App.Enums.AdviceStatusResult;
group_id: string | null;
visible_in_group: boolean;
};
export type AdviceStatusNamesData = {
id: string;
name: string;
result: App.Enums.AdviceStatusResult;
};
export type CategoryData = {
id: string;
name: string;
image_path: string | null;
map_points_count: number;
created_at: string | null;
};
export type DataProtectedAdviceData = {
id: string;
first_name: string;
last_name: string;
street: string;
street_number: string;
zip: string;
city: string;
email: string | null;
phone: string | null;
commentary: string | null;
advisor_id: string | null;
advice_status_id: string | null;
lng: number | null;
lat: number | null;
type: App.Enums.AdviceType | null;
created_at: any;
updated_at: any;
distance: number | null;
shares_ids: Array<any>;
place_notes: string | null;
house_type: App.Enums.HouseType | null;
landlord_exists: boolean | null;
help_type_place: boolean | null;
help_type_technical: boolean | null;
help_type_bureaucracy: boolean | null;
help_type_other: boolean | null;
result: App.Enums.AdviceStatusResult;
can_edit: boolean | null;
group_id: string | null;
};
export type FormDefinitionData = {
id: string;
name: string;
description: string | null;
is_active: boolean;
fields: Array<App.Data.FormFieldData>;
group_id: string;
};
export type FormFieldData = {
id: string;
type: App.Enums.FieldType;
label: string;
options: Array<App.Data.FormFieldOptionData>;
placeholder: string | null;
help_text: string | null;
required: boolean;
default_value: string | null;
sort_order: number;
min_length: number | null;
max_length: number | null;
min_value: number | null;
max_value: number | null;
accepted_file_types: Array<any> | null;
};
export type FormFieldOptionData = {
id: string;
label: string;
value: string;
sort_order: number;
is_default: boolean;
is_required: boolean;
};
export type FormSubmissionData = {
id: string;
form_name: string;
fields: Array<App.Data.SubmissionFieldData>;
submitted_at: any;
seen: boolean;
};
export type GroupBaseData = {
id: string;
name: string;
description: string | null;
logo_path: string | null;
};
export type GroupData = {
users_count: number;
advices_count: number;
id: string;
name: string;
description: string | null;
logo_path: string | null;
parent_id: string | null;
accepts_transfers: boolean;
userCanActAsAdmin: boolean;
};
export type GroupMapData = {
polygon: App.ValueObjects.Polygon;
center: App.ValueObjects.Coordinate;
name: string;
logo_path: string | null;
};
export type GroupTreeItem = {
id: string;
name: string;
selected: boolean;
expanded: boolean;
parent_id: string | null;
logo_path: string | null;
};
export type GroupUserData = {
id: string;
name: string;
email: string;
is_admin: boolean;
};
export type MapPointData = {
id: string;
coordinate: App.ValueObjects.Coordinate;
title: string;
description: string;
published: boolean;
userReadablePointableType: string;
created_at: any;
category: App.Data.CategoryData | null;
category_id: string | null;
};
export type PaginationData = {
total: number;
perPage: number;
currentPage: number;
lastPage: number;
};
export type SubmissionFieldData = {
value: number | string | Array<string> | null;
field: App.Data.FormFieldData;
};
export type UserData = {
id: string;
first_name: string;
last_name: string;
name: string;
email: string;
is_acting_as_admin: boolean;
lat: number | null;
long: number | null;
profile_picture: string | null;
advice_radius: number | null;
street: string | null;
street_number: string | null;
city: string | null;
zip: string | null;
is_admin: boolean;
};
}
declare namespace App.Data.Pages {
export type GroupsIndexData = {
groupTreeItems: Array<App.Data.GroupTreeItem>;
groups: Array<App.Data.GroupData>;
canCreateRootGroup: boolean;
selectedGroup: App.Data.GroupData | null;
polygon: App.ValueObjects.Polygon | null;
canEditGroup: boolean;
canCreateGroups: boolean;
};
}
declare namespace App.Enums {
export type AdviceStatusResult = 0 | 1 | 2 | 3;
export type AdviceType = 0 | 1 | 2;
export type FieldType = 'text' | 'textarea' | 'number' | 'email' | 'phone' | 'select' | 'radio' | 'checkbox' | 'file' | 'date' | 'geo_coordinate' | 'address';
export type HouseType = 0 | 1 | 2;
}
declare namespace App.ValueObjects {
export type Address = {
street: string;
street_number: string;
zip: string;
city: string;
};
export type Coordinate = {
lat: number;
lng: number;
};
export type Polygon = {
coordinates: Array<App.ValueObjects.Coordinate>;
};
}
