<?php

namespace App;

use Override;
use Spatie\TypeScriptTransformer\Collections\TransformedCollection;
use Spatie\TypeScriptTransformer\Data\WriteableFile;
use Spatie\TypeScriptTransformer\Transformed\Transformed;
use Spatie\TypeScriptTransformer\Writers\GlobalNamespaceWriter;

class TypescriptWriter extends GlobalNamespaceWriter
{
    /**
     * @param  array<int, Transformed>  $transformed
     * @return array<int, WriteableFile>
     */
    #[Override]
    public function output(
        array $transformed,
        TransformedCollection $transformedCollection,
    ): array {
        $header = '// this file is auto-generated by the command: php artisan typescript:transform'.PHP_EOL
            .'// do not edit this file manually'.PHP_EOL;

        return array_map(
            fn (WriteableFile $file): WriteableFile => new WriteableFile(
                $file->path,
                $header.$file->contents,
                $file->changed,
            ),
            parent::output($transformed, $transformedCollection),
        );
    }
}
