<?php

namespace App;

use Spatie\TypeScriptTransformer\Structures\TypesCollection;
use Spatie\TypeScriptTransformer\Writers\TypeDefinitionWriter;

class TypescriptWriter extends TypeDefinitionWriter
{
    #[\Override]
    public function format(TypesCollection $collection): string
    {
        $output = '// this file is auto-generated by the command: php artisan typescript:transform' . PHP_EOL;
        $output .= '// do not edit this file manually' . PHP_EOL;
        $output .= parent::format($collection);

        return $output;
    }
}
